# Generated by Django 4.2.4 on 2023-08-15 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='amount',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='color',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='prime_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='size',
            field=models.CharField(default='Uncategorized', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='description',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
