# Generated by Django 4.2.4 on 2023-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('orders', '0004_alter_salesorder_category_alter_salesorder_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='item',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
