# Generated by Django 4.2.4 on 2023-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=0, max_length=255)),
                ('model', models.CharField(default=0, max_length=255)),
                ('movement', models.CharField(default=0, max_length=255)),
                ('case', models.CharField(default=0, max_length=255)),
                ('dial', models.CharField(default=0, max_length=255)),
                ('crystal', models.CharField(default=0, max_length=255)),
                ('bezel', models.CharField(default=0, max_length=255)),
                ('bracelet', models.CharField(default=0, max_length=255)),
                ('bracelet_length', models.CharField(default=0, max_length=255)),
                ('production_year', models.CharField(default=0, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(default=0, max_length=600)),
            ],
        ),
    ]
